// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: org/lineageos/updater/protos/build.proto

package org.lineageos.updater.protos;

/**
 * Protobuf type {@code appOTA.Build}
 */
public  final class Build extends
    com.google.protobuf.GeneratedMessageLite<
        Build, Build.Builder> implements
    // @@protoc_insertion_point(message_implements:appOTA.Build)
    BuildOrBuilder {
  private Build() {
    name_ = "";
    version_ = "";
    buildId_ = "";
    channel_ = "";
    url_ = "";
    sha256_ = "";
  }
  public static final int NAME_FIELD_NUMBER = 1;
  private java.lang.String name_;
  /**
   * <code>optional string name = 1;</code>
   */
  public java.lang.String getName() {
    return name_;
  }
  /**
   * <code>optional string name = 1;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(name_);
  }
  /**
   * <code>optional string name = 1;</code>
   */
  private void setName(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    name_ = value;
  }
  /**
   * <code>optional string name = 1;</code>
   */
  private void clearName() {
    
    name_ = getDefaultInstance().getName();
  }
  /**
   * <code>optional string name = 1;</code>
   */
  private void setNameBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    name_ = value.toStringUtf8();
  }

  public static final int VERSION_FIELD_NUMBER = 2;
  private java.lang.String version_;
  /**
   * <code>optional string version = 2;</code>
   */
  public java.lang.String getVersion() {
    return version_;
  }
  /**
   * <code>optional string version = 2;</code>
   */
  public com.google.protobuf.ByteString
      getVersionBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(version_);
  }
  /**
   * <code>optional string version = 2;</code>
   */
  private void setVersion(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    version_ = value;
  }
  /**
   * <code>optional string version = 2;</code>
   */
  private void clearVersion() {
    
    version_ = getDefaultInstance().getVersion();
  }
  /**
   * <code>optional string version = 2;</code>
   */
  private void setVersionBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    version_ = value.toStringUtf8();
  }

  public static final int BUILDID_FIELD_NUMBER = 3;
  private java.lang.String buildId_;
  /**
   * <code>optional string buildId = 3;</code>
   */
  public java.lang.String getBuildId() {
    return buildId_;
  }
  /**
   * <code>optional string buildId = 3;</code>
   */
  public com.google.protobuf.ByteString
      getBuildIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(buildId_);
  }
  /**
   * <code>optional string buildId = 3;</code>
   */
  private void setBuildId(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    buildId_ = value;
  }
  /**
   * <code>optional string buildId = 3;</code>
   */
  private void clearBuildId() {
    
    buildId_ = getDefaultInstance().getBuildId();
  }
  /**
   * <code>optional string buildId = 3;</code>
   */
  private void setBuildIdBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    buildId_ = value.toStringUtf8();
  }

  public static final int SIZE_FIELD_NUMBER = 4;
  private int size_;
  /**
   * <code>optional int32 size = 4;</code>
   */
  public int getSize() {
    return size_;
  }
  /**
   * <code>optional int32 size = 4;</code>
   */
  private void setSize(int value) {
    
    size_ = value;
  }
  /**
   * <code>optional int32 size = 4;</code>
   */
  private void clearSize() {
    
    size_ = 0;
  }

  public static final int CREATED_FIELD_NUMBER = 5;
  private long created_;
  /**
   * <code>optional int64 created = 5;</code>
   */
  public long getCreated() {
    return created_;
  }
  /**
   * <code>optional int64 created = 5;</code>
   */
  private void setCreated(long value) {
    
    created_ = value;
  }
  /**
   * <code>optional int64 created = 5;</code>
   */
  private void clearCreated() {
    
    created_ = 0L;
  }

  public static final int CHANNEL_FIELD_NUMBER = 6;
  private java.lang.String channel_;
  /**
   * <code>optional string channel = 6;</code>
   */
  public java.lang.String getChannel() {
    return channel_;
  }
  /**
   * <code>optional string channel = 6;</code>
   */
  public com.google.protobuf.ByteString
      getChannelBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(channel_);
  }
  /**
   * <code>optional string channel = 6;</code>
   */
  private void setChannel(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    channel_ = value;
  }
  /**
   * <code>optional string channel = 6;</code>
   */
  private void clearChannel() {
    
    channel_ = getDefaultInstance().getChannel();
  }
  /**
   * <code>optional string channel = 6;</code>
   */
  private void setChannelBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    channel_ = value.toStringUtf8();
  }

  public static final int URL_FIELD_NUMBER = 7;
  private java.lang.String url_;
  /**
   * <code>optional string url = 7;</code>
   */
  public java.lang.String getUrl() {
    return url_;
  }
  /**
   * <code>optional string url = 7;</code>
   */
  public com.google.protobuf.ByteString
      getUrlBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(url_);
  }
  /**
   * <code>optional string url = 7;</code>
   */
  private void setUrl(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    url_ = value;
  }
  /**
   * <code>optional string url = 7;</code>
   */
  private void clearUrl() {
    
    url_ = getDefaultInstance().getUrl();
  }
  /**
   * <code>optional string url = 7;</code>
   */
  private void setUrlBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    url_ = value.toStringUtf8();
  }

  public static final int SHA256_FIELD_NUMBER = 8;
  private java.lang.String sha256_;
  /**
   * <code>optional string sha256 = 8;</code>
   */
  public java.lang.String getSha256() {
    return sha256_;
  }
  /**
   * <code>optional string sha256 = 8;</code>
   */
  public com.google.protobuf.ByteString
      getSha256Bytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(sha256_);
  }
  /**
   * <code>optional string sha256 = 8;</code>
   */
  private void setSha256(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    sha256_ = value;
  }
  /**
   * <code>optional string sha256 = 8;</code>
   */
  private void clearSha256() {
    
    sha256_ = getDefaultInstance().getSha256();
  }
  /**
   * <code>optional string sha256 = 8;</code>
   */
  private void setSha256Bytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    sha256_ = value.toStringUtf8();
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!name_.isEmpty()) {
      output.writeString(1, getName());
    }
    if (!version_.isEmpty()) {
      output.writeString(2, getVersion());
    }
    if (!buildId_.isEmpty()) {
      output.writeString(3, getBuildId());
    }
    if (size_ != 0) {
      output.writeInt32(4, size_);
    }
    if (created_ != 0L) {
      output.writeInt64(5, created_);
    }
    if (!channel_.isEmpty()) {
      output.writeString(6, getChannel());
    }
    if (!url_.isEmpty()) {
      output.writeString(7, getUrl());
    }
    if (!sha256_.isEmpty()) {
      output.writeString(8, getSha256());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (!name_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(1, getName());
    }
    if (!version_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(2, getVersion());
    }
    if (!buildId_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(3, getBuildId());
    }
    if (size_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, size_);
    }
    if (created_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, created_);
    }
    if (!channel_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(6, getChannel());
    }
    if (!url_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(7, getUrl());
    }
    if (!sha256_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(8, getSha256());
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static org.lineageos.updater.protos.Build parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.lineageos.updater.protos.Build parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.lineageos.updater.protos.Build parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.lineageos.updater.protos.Build parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.lineageos.updater.protos.Build parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.lineageos.updater.protos.Build parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.lineageos.updater.protos.Build parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static org.lineageos.updater.protos.Build parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.lineageos.updater.protos.Build parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.lineageos.updater.protos.Build parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.lineageos.updater.protos.Build prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code appOTA.Build}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        org.lineageos.updater.protos.Build, Builder> implements
      // @@protoc_insertion_point(builder_implements:appOTA.Build)
      org.lineageos.updater.protos.BuildOrBuilder {
    // Construct using org.lineageos.updater.protos.Build.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional string name = 1;</code>
     */
    public java.lang.String getName() {
      return instance.getName();
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      return instance.getNameBytes();
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public Builder setName(
        java.lang.String value) {
      copyOnWrite();
      instance.setName(value);
      return this;
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public Builder clearName() {
      copyOnWrite();
      instance.clearName();
      return this;
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNameBytes(value);
      return this;
    }

    /**
     * <code>optional string version = 2;</code>
     */
    public java.lang.String getVersion() {
      return instance.getVersion();
    }
    /**
     * <code>optional string version = 2;</code>
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      return instance.getVersionBytes();
    }
    /**
     * <code>optional string version = 2;</code>
     */
    public Builder setVersion(
        java.lang.String value) {
      copyOnWrite();
      instance.setVersion(value);
      return this;
    }
    /**
     * <code>optional string version = 2;</code>
     */
    public Builder clearVersion() {
      copyOnWrite();
      instance.clearVersion();
      return this;
    }
    /**
     * <code>optional string version = 2;</code>
     */
    public Builder setVersionBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setVersionBytes(value);
      return this;
    }

    /**
     * <code>optional string buildId = 3;</code>
     */
    public java.lang.String getBuildId() {
      return instance.getBuildId();
    }
    /**
     * <code>optional string buildId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getBuildIdBytes() {
      return instance.getBuildIdBytes();
    }
    /**
     * <code>optional string buildId = 3;</code>
     */
    public Builder setBuildId(
        java.lang.String value) {
      copyOnWrite();
      instance.setBuildId(value);
      return this;
    }
    /**
     * <code>optional string buildId = 3;</code>
     */
    public Builder clearBuildId() {
      copyOnWrite();
      instance.clearBuildId();
      return this;
    }
    /**
     * <code>optional string buildId = 3;</code>
     */
    public Builder setBuildIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setBuildIdBytes(value);
      return this;
    }

    /**
     * <code>optional int32 size = 4;</code>
     */
    public int getSize() {
      return instance.getSize();
    }
    /**
     * <code>optional int32 size = 4;</code>
     */
    public Builder setSize(int value) {
      copyOnWrite();
      instance.setSize(value);
      return this;
    }
    /**
     * <code>optional int32 size = 4;</code>
     */
    public Builder clearSize() {
      copyOnWrite();
      instance.clearSize();
      return this;
    }

    /**
     * <code>optional int64 created = 5;</code>
     */
    public long getCreated() {
      return instance.getCreated();
    }
    /**
     * <code>optional int64 created = 5;</code>
     */
    public Builder setCreated(long value) {
      copyOnWrite();
      instance.setCreated(value);
      return this;
    }
    /**
     * <code>optional int64 created = 5;</code>
     */
    public Builder clearCreated() {
      copyOnWrite();
      instance.clearCreated();
      return this;
    }

    /**
     * <code>optional string channel = 6;</code>
     */
    public java.lang.String getChannel() {
      return instance.getChannel();
    }
    /**
     * <code>optional string channel = 6;</code>
     */
    public com.google.protobuf.ByteString
        getChannelBytes() {
      return instance.getChannelBytes();
    }
    /**
     * <code>optional string channel = 6;</code>
     */
    public Builder setChannel(
        java.lang.String value) {
      copyOnWrite();
      instance.setChannel(value);
      return this;
    }
    /**
     * <code>optional string channel = 6;</code>
     */
    public Builder clearChannel() {
      copyOnWrite();
      instance.clearChannel();
      return this;
    }
    /**
     * <code>optional string channel = 6;</code>
     */
    public Builder setChannelBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setChannelBytes(value);
      return this;
    }

    /**
     * <code>optional string url = 7;</code>
     */
    public java.lang.String getUrl() {
      return instance.getUrl();
    }
    /**
     * <code>optional string url = 7;</code>
     */
    public com.google.protobuf.ByteString
        getUrlBytes() {
      return instance.getUrlBytes();
    }
    /**
     * <code>optional string url = 7;</code>
     */
    public Builder setUrl(
        java.lang.String value) {
      copyOnWrite();
      instance.setUrl(value);
      return this;
    }
    /**
     * <code>optional string url = 7;</code>
     */
    public Builder clearUrl() {
      copyOnWrite();
      instance.clearUrl();
      return this;
    }
    /**
     * <code>optional string url = 7;</code>
     */
    public Builder setUrlBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUrlBytes(value);
      return this;
    }

    /**
     * <code>optional string sha256 = 8;</code>
     */
    public java.lang.String getSha256() {
      return instance.getSha256();
    }
    /**
     * <code>optional string sha256 = 8;</code>
     */
    public com.google.protobuf.ByteString
        getSha256Bytes() {
      return instance.getSha256Bytes();
    }
    /**
     * <code>optional string sha256 = 8;</code>
     */
    public Builder setSha256(
        java.lang.String value) {
      copyOnWrite();
      instance.setSha256(value);
      return this;
    }
    /**
     * <code>optional string sha256 = 8;</code>
     */
    public Builder clearSha256() {
      copyOnWrite();
      instance.clearSha256();
      return this;
    }
    /**
     * <code>optional string sha256 = 8;</code>
     */
    public Builder setSha256Bytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setSha256Bytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:appOTA.Build)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new org.lineageos.updater.protos.Build();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        org.lineageos.updater.protos.Build other = (org.lineageos.updater.protos.Build) arg1;
        name_ = visitor.visitString(!name_.isEmpty(), name_,
            !other.name_.isEmpty(), other.name_);
        version_ = visitor.visitString(!version_.isEmpty(), version_,
            !other.version_.isEmpty(), other.version_);
        buildId_ = visitor.visitString(!buildId_.isEmpty(), buildId_,
            !other.buildId_.isEmpty(), other.buildId_);
        size_ = visitor.visitInt(size_ != 0, size_,
            other.size_ != 0, other.size_);
        created_ = visitor.visitLong(created_ != 0L, created_,
            other.created_ != 0L, other.created_);
        channel_ = visitor.visitString(!channel_.isEmpty(), channel_,
            !other.channel_.isEmpty(), other.channel_);
        url_ = visitor.visitString(!url_.isEmpty(), url_,
            !other.url_.isEmpty(), other.url_);
        sha256_ = visitor.visitString(!sha256_.isEmpty(), sha256_,
            !other.sha256_.isEmpty(), other.sha256_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                String s = input.readStringRequireUtf8();

                name_ = s;
                break;
              }
              case 18: {
                String s = input.readStringRequireUtf8();

                version_ = s;
                break;
              }
              case 26: {
                String s = input.readStringRequireUtf8();

                buildId_ = s;
                break;
              }
              case 32: {

                size_ = input.readInt32();
                break;
              }
              case 40: {

                created_ = input.readInt64();
                break;
              }
              case 50: {
                String s = input.readStringRequireUtf8();

                channel_ = s;
                break;
              }
              case 58: {
                String s = input.readStringRequireUtf8();

                url_ = s;
                break;
              }
              case 66: {
                String s = input.readStringRequireUtf8();

                sha256_ = s;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (org.lineageos.updater.protos.Build.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:appOTA.Build)
  private static final org.lineageos.updater.protos.Build DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Build();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static org.lineageos.updater.protos.Build getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Build> PARSER;

  public static com.google.protobuf.Parser<Build> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

