// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: org/lineageos/updater/protos/build.proto

package org.lineageos.updater.protos;

public final class BuildProtos {
  private BuildProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
