// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: org/lineageos/updater/protos/build.proto

package org.lineageos.updater.protos;

public interface BuildListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:appOTA.BuildList)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .appOTA.Build builds = 1;</code>
   */
  java.util.List<org.lineageos.updater.protos.Build> 
      getBuildsList();
  /**
   * <code>repeated .appOTA.Build builds = 1;</code>
   */
  org.lineageos.updater.protos.Build getBuilds(int index);
  /**
   * <code>repeated .appOTA.Build builds = 1;</code>
   */
  int getBuildsCount();
}
